import { db } from '@/db';
import { apps } from '@/db/schema';

async function main() {
    const sampleApps = [
        {
            name: 'HEIC Converter',
            slug: 'heic-converter',
            description: 'Download HEIC Converter by Sindre Sorhus on the App Store. See screenshots ratings and reviews user tips and more games like HEIC Converter.',
            shortDescription: 'Download HEIC Converter by Sindre Sorhus on the...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281811/snapcloud/j84cnr7crpidskvhvas3.png',
            downloadUrl: 'https://apps.apple.com/us/app/heic-converter/id1294126402?mt=12',
            platform: 'macOS',
            category: 'Photo Tool',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281811/snapcloud/j84cnr7crpidskvhvas3.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 342,
            createdAt: new Date('2023-03-15').toISOString(),
        },
        {
            name: 'Blitzit',
            slug: 'blitzit',
            description: 'Blitzit is a simple to-do list and ever-visible timer that supercharges your productivity helping you prioritize what matters eliminate distractions and get things done in an unbreakable flow state. Integrates with Notion & Google Calendar (more soon).',
            shortDescription: 'Blitzit is a simple to-do list and ever-visible...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281925/snapcloud/qdu38ujr3ijhvc3vph3f.png',
            downloadUrl: 'https://www.blitzit.app/?via=toolfolio',
            platform: 'macOS',
            category: 'Productivity Tracker',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281925/snapcloud/qdu38ujr3ijhvc3vph3f.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 567,
            createdAt: new Date('2023-05-20').toISOString(),
        },
        {
            name: 'VoiceTypr',
            slug: 'voicetypr',
            description: 'Offline AI voice to text app that runs locally. Private by default. Pay once use forever.',
            shortDescription: 'Offline AI voice to text app that runs locally....',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281930/snapcloud/ithe1j5iejsefot59vzh.png',
            downloadUrl: 'https://voicetypr.com/',
            platform: 'macOS',
            category: 'Voice Dictation',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281930/snapcloud/ithe1j5iejsefot59vzh.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 423,
            createdAt: new Date('2023-07-10').toISOString(),
        },
        {
            name: 'vibecode',
            slug: 'vibecode',
            description: 'Turn your app idea into reality in minutes with Vibecode. The best AI-powered mobile app builder that lets you design build and publish apps to the App Store without coding.',
            shortDescription: 'Turn your app idea into reality in minutes with...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281937/snapcloud/yzd3h3hfyboje475oxrl.png',
            downloadUrl: 'https://www.vibecodeapp.com/',
            platform: 'iOS',
            category: 'App Builder',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281937/snapcloud/yzd3h3hfyboje475oxrl.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 689,
            createdAt: new Date('2023-08-25').toISOString(),
        },
        {
            name: 'Wispr Flow',
            slug: 'wispr-flow',
            description: 'Flow makes writing quick and clear with seamless voice dictation. It is the fastest smartest way to type with your voice.',
            shortDescription: 'Flow makes writing quick and clear with seamles...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281954/snapcloud/rp1t2uq6cy7jcqzomxdh.png',
            downloadUrl: 'https://wisprflow.ai/?via=dudu&dub_id=7DiLfa2YGM1CCENW',
            platform: 'macOS',
            category: 'Voice Dictation',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281954/snapcloud/rp1t2uq6cy7jcqzomxdh.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 512,
            createdAt: new Date('2023-09-12').toISOString(),
        },
        {
            name: 'Milanote',
            slug: 'milanote',
            description: 'An easy-to-use tool to organize your ideas and creative projects into visual boards. It\'s designed for creative professionals and teams for tasks like moodboarding brainstorming storyboarding note-taking and project management.',
            shortDescription: 'An easy-to-use tool to organize your ideas and c...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281959/snapcloud/xdkgi9xgfhbjjzzlcjnt.png',
            downloadUrl: 'https://milanote.com/',
            platform: 'macOS',
            category: 'Project Organizer',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281959/snapcloud/xdkgi9xgfhbjjzzlcjnt.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 734,
            createdAt: new Date('2023-10-05').toISOString(),
        },
        {
            name: 'Shortcat',
            slug: 'shortcat',
            description: 'A universal command palette for your Mac that lets you control the macOS user interface masterfully minus the mouse. It allows you to click buttons focus text fields invoke menu commands and switch windows using just a few keystrokes.',
            shortDescription: 'A universal command palette for your Mac that le...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281964/snapcloud/xv5rx8kkasgusz6msudt.png',
            downloadUrl: 'https://shortcat.app/',
            platform: 'macOS',
            category: 'Mac Productivity',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281964/snapcloud/xv5rx8kkasgusz6msudt.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 298,
            createdAt: new Date('2023-11-18').toISOString(),
        },
        {
            name: 'Alfred',
            slug: 'alfred',
            description: 'Alfred is a productivity application for macOS which boosts your efficiency with hotkeys keywords and text expansion. Search your Mac and the web and control your Mac using custom actions with the Powerpack.',
            shortDescription: 'Alfred is a productivity application for macOS w...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281969/snapcloud/spwwo5to0xvixekaervs.png',
            downloadUrl: 'https://www.alfredapp.com/',
            platform: 'macOS',
            category: 'Productivity Tool',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281969/snapcloud/spwwo5to0xvixekaervs.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 621,
            createdAt: new Date('2023-12-02').toISOString(),
        },
        {
            name: 'Nucleo',
            slug: 'nucleo',
            description: 'Explore the Nucleo icons 30000 icons for UIs presentations and print projects. Download instantly or use them via our web and native apps.',
            shortDescription: 'Explore the Nucleo icons 30000 icons for UIs pre...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281974/snapcloud/gcsledchlc6wy32jqvgk.png',
            downloadUrl: 'https://nucleoapp.com/',
            platform: 'macOS',
            category: 'Design Tools',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281974/snapcloud/gcsledchlc6wy32jqvgk.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 478,
            createdAt: new Date('2024-01-14').toISOString(),
        },
        {
            name: 'Notch Nook',
            slug: 'notch-nook',
            description: 'A whole new way full of possibilities of using your macos notch',
            shortDescription: 'A whole new way full of possibilities of using y...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281978/snapcloud/nqlz3ksnhcexubbt38ah.png',
            downloadUrl: 'https://lo.cafe/notchnook',
            platform: 'macOS',
            category: 'Productivity',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281978/snapcloud/nqlz3ksnhcexubbt38ah.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 389,
            createdAt: new Date('2024-02-08').toISOString(),
        },
        {
            name: 'Setapp',
            slug: 'setapp',
            description: 'Setapp offers access to over 240 macOS and iOS apps for one subscription. Discover powerful apps for productivity creativity and utilities.',
            shortDescription: 'Setapp offers access to over 240 macOS and iOS a...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281982/snapcloud/example1.png',
            downloadUrl: 'https://setapp.com/',
            platform: 'macOS',
            category: 'App Subscription',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281982/snapcloud/example1.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 756,
            createdAt: new Date('2024-03-03').toISOString(),
        },
        {
            name: 'Numi',
            slug: 'numi',
            description: 'Beautiful calculator app for Mac that combines text and calculation. Type your calculations naturally and see results instantly.',
            shortDescription: 'Beautiful calculator app for Mac that combines t...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281986/snapcloud/example2.png',
            downloadUrl: 'https://numi.app/',
            platform: 'macOS',
            category: 'Calculator',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281986/snapcloud/example2.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 267,
            createdAt: new Date('2024-03-22').toISOString(),
        },
        {
            name: 'Week Number',
            slug: 'week-number',
            description: 'Simple menu bar app that shows the current week number. Perfect for planning and scheduling.',
            shortDescription: 'Simple menu bar app that shows the current week ...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281990/snapcloud/example3.png',
            downloadUrl: 'https://weeknumber.app/',
            platform: 'macOS',
            category: 'Calendar Widget',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281990/snapcloud/example3.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 194,
            createdAt: new Date('2024-04-10').toISOString(),
        },
        {
            name: 'Cyber',
            slug: 'cyber',
            description: 'Keep your Mac secure with real-time security monitoring and protection. Lightweight and powerful.',
            shortDescription: 'Keep your Mac secure with real-time security mon...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281994/snapcloud/example4.png',
            downloadUrl: 'https://cyber.app/',
            platform: 'macOS',
            category: 'Security',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281994/snapcloud/example4.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 543,
            createdAt: new Date('2024-05-05').toISOString(),
        },
        {
            name: 'Pieoneer',
            slug: 'pieoneer',
            description: 'Create beautiful pie charts and data visualizations with ease. Export to multiple formats.',
            shortDescription: 'Create beautiful pie charts and data visualizati...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281998/snapcloud/example5.png',
            downloadUrl: 'https://pieoneer.app/',
            platform: 'macOS',
            category: 'Chart Tool',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764281998/snapcloud/example5.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 318,
            createdAt: new Date('2024-05-28').toISOString(),
        },
        {
            name: 'Blip',
            slug: 'blip',
            description: 'Fast and private messaging app for Mac. Stay connected with friends and colleagues.',
            shortDescription: 'Fast and private messaging app for Mac. Stay con...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282002/snapcloud/example6.png',
            downloadUrl: 'https://blip.app/',
            platform: 'macOS',
            category: 'Messaging',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282002/snapcloud/example6.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 672,
            createdAt: new Date('2024-06-14').toISOString(),
        },
        {
            name: 'Cap',
            slug: 'cap',
            description: 'Beautiful screen recording for macOS. Record share and collaborate with ease.',
            shortDescription: 'Beautiful screen recording for macOS. Record sha...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282006/snapcloud/example7.png',
            downloadUrl: 'https://cap.so/',
            platform: 'macOS',
            category: 'Screen Recording',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282006/snapcloud/example7.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 445,
            createdAt: new Date('2024-07-02').toISOString(),
        },
        {
            name: 'TranslateAir',
            slug: 'translateair',
            description: 'Instant translation in any app. Translate text on your screen with a simple keyboard shortcut.',
            shortDescription: 'Instant translation in any app. Translate text o...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282010/snapcloud/example8.png',
            downloadUrl: 'https://translateair.app/',
            platform: 'macOS',
            category: 'Translation',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282010/snapcloud/example8.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 509,
            createdAt: new Date('2024-07-19').toISOString(),
        },
        {
            name: 'Usage',
            slug: 'usage',
            description: 'Monitor your Mac\'s CPU memory disk and network usage. Beautiful design and real-time stats.',
            shortDescription: 'Monitor your Mac\'s CPU memory disk and network u...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282014/snapcloud/example9.png',
            downloadUrl: 'https://usage.app/',
            platform: 'macOS',
            category: 'System Monitor',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282014/snapcloud/example9.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 381,
            createdAt: new Date('2024-08-07').toISOString(),
        },
        {
            name: 'Loop',
            slug: 'loop',
            description: 'Elegant window management for macOS. Organize windows with keyboard shortcuts and gestures.',
            shortDescription: 'Elegant window management for macOS. Organize wi...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282018/snapcloud/example10.png',
            downloadUrl: 'https://loopapp.co/',
            platform: 'macOS',
            category: 'Window Manager',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282018/snapcloud/example10.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 628,
            createdAt: new Date('2024-08-25').toISOString(),
        },
        {
            name: 'PixelSnap',
            slug: 'pixelsnap',
            description: 'Measure anything on your screen. Perfect for designers and developers.',
            shortDescription: 'Measure anything on your screen. Perfect for des...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282022/snapcloud/example11.png',
            downloadUrl: 'https://pixelsnap.app/',
            platform: 'macOS',
            category: 'Design Tool',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282022/snapcloud/example11.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 234,
            createdAt: new Date('2024-09-12').toISOString(),
        },
        {
            name: 'Ebb',
            slug: 'ebb',
            description: 'Beautiful Pomodoro timer for Mac. Stay focused and productive with time tracking.',
            shortDescription: 'Beautiful Pomodoro timer for Mac. Stay focused a...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282026/snapcloud/example12.png',
            downloadUrl: 'https://ebb.app/',
            platform: 'macOS',
            category: 'Focus Timer',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282026/snapcloud/example12.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 412,
            createdAt: new Date('2024-09-30').toISOString(),
        },
        {
            name: 'SuperClick',
            slug: 'superclick',
            description: 'Enhance your clicking experience with customizable gestures and shortcuts.',
            shortDescription: 'Enhance your clicking experience with customizab...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282030/snapcloud/example13.png',
            downloadUrl: 'https://superclick.app/',
            platform: 'macOS',
            category: 'Mouse Enhancement',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282030/snapcloud/example13.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 289,
            createdAt: new Date('2024-10-15').toISOString(),
        },
        {
            name: 'Picasso App',
            slug: 'picasso-app',
            description: 'Digital painting and drawing app for creative professionals. Powerful brushes and tools.',
            shortDescription: 'Digital painting and drawing app for creative pr...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282034/snapcloud/example14.png',
            downloadUrl: 'https://picasso.app/',
            platform: 'macOS',
            category: 'Art Tool',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282034/snapcloud/example14.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 558,
            createdAt: new Date('2024-11-03').toISOString(),
        },
        {
            name: 'Compresto',
            slug: 'compresto',
            description: 'Fast and efficient file compression for Mac. Reduce file sizes without quality loss.',
            shortDescription: 'Fast and efficient file compression for Mac. Red...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282038/snapcloud/example15.png',
            downloadUrl: 'https://compresto.app/',
            platform: 'macOS',
            category: 'File Compression',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282038/snapcloud/example15.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 367,
            createdAt: new Date('2024-11-20').toISOString(),
        },
        {
            name: 'Raindrop',
            slug: 'raindrop',
            description: 'All-in-one bookmark manager. Save organize and access your favorite links from anywhere.',
            shortDescription: 'All-in-one bookmark manager. Save organize and a...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282042/snapcloud/example16.png',
            downloadUrl: 'https://raindrop.io/',
            platform: 'macOS',
            category: 'Bookmark Manager',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282042/snapcloud/example16.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 695,
            createdAt: new Date('2024-12-08').toISOString(),
        },
        {
            name: 'Constella',
            slug: 'constella',
            description: 'Explore the night sky with this beautiful astronomy app. Track stars planets and constellations.',
            shortDescription: 'Explore the night sky with this beautiful astron...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282046/snapcloud/example17.png',
            downloadUrl: 'https://constella.app/',
            platform: 'macOS',
            category: 'Astronomy',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282046/snapcloud/example17.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 223,
            createdAt: new Date('2023-02-12').toISOString(),
        },
        {
            name: 'Command X',
            slug: 'command-x',
            description: 'Powerful file management for macOS. Cut copy move and organize files efficiently.',
            shortDescription: 'Powerful file management for macOS. Cut copy mov...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282050/snapcloud/example18.png',
            downloadUrl: 'https://commandx.app/',
            platform: 'macOS',
            category: 'File Manager',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282050/snapcloud/example18.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 487,
            createdAt: new Date('2023-04-05').toISOString(),
        },
        {
            name: 'KeyScreen',
            slug: 'keyscreen',
            description: 'Display keystrokes on screen for presentations and tutorials. Perfect for educators.',
            shortDescription: 'Display keystrokes on screen for presentations a...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282054/snapcloud/example19.png',
            downloadUrl: 'https://keyscreen.app/',
            platform: 'macOS',
            category: 'Keystroke Display',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282054/snapcloud/example19.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 312,
            createdAt: new Date('2023-06-18').toISOString(),
        },
        {
            name: 'Octarine',
            slug: 'octarine',
            description: 'Professional color picker for designers. Pick organize and manage colors from anywhere.',
            shortDescription: 'Professional color picker for designers. Pick or...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282058/snapcloud/example20.png',
            downloadUrl: 'https://octarine.app/',
            platform: 'macOS',
            category: 'Color Picker',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282058/snapcloud/example20.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 456,
            createdAt: new Date('2023-08-09').toISOString(),
        },
        {
            name: 'Raycast',
            slug: 'raycast',
            description: 'Blazingly fast extensible launcher for Mac. Control your tools with extensions.',
            shortDescription: 'Blazingly fast extensible launcher for Mac. Cont...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282062/snapcloud/example21.png',
            downloadUrl: 'https://raycast.com/',
            platform: 'macOS',
            category: 'Launcher',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282062/snapcloud/example21.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 792,
            createdAt: new Date('2023-09-27').toISOString(),
        },
        {
            name: 'Paste',
            slug: 'paste',
            description: 'The best clipboard manager for Mac. Never lose what you copy again.',
            shortDescription: 'The best clipboard manager for Mac. Never lose w...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282066/snapcloud/example22.png',
            downloadUrl: 'https://paste.app/',
            platform: 'macOS',
            category: 'Clipboard Manager',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282066/snapcloud/example22.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 634,
            createdAt: new Date('2023-11-14').toISOString(),
        },
        {
            name: 'RightFont',
            slug: 'rightfont',
            description: 'Professional font manager for Mac. Preview organize and activate fonts instantly.',
            shortDescription: 'Professional font manager for Mac. Preview organ...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282070/snapcloud/example23.png',
            downloadUrl: 'https://rightfontapp.com/',
            platform: 'macOS',
            category: 'Font Manager',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282070/snapcloud/example23.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 378,
            createdAt: new Date('2024-01-02').toISOString(),
        },
        {
            name: 'Keystroke Pro',
            slug: 'keystroke-pro',
            description: 'Advanced keyboard customization for power users. Create custom shortcuts and macros.',
            shortDescription: 'Advanced keyboard customization for power users....',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282074/snapcloud/example24.png',
            downloadUrl: 'https://keystrokepro.app/',
            platform: 'macOS',
            category: 'Keyboard Tool',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282074/snapcloud/example24.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 521,
            createdAt: new Date('2024-02-18').toISOString(),
        },
        {
            name: 'Harmony AI',
            slug: 'harmony-ai',
            description: 'AI-powered assistant for macOS. Get help with writing coding and more.',
            shortDescription: 'AI-powered assistant for macOS. Get help with wr...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282078/snapcloud/example25.png',
            downloadUrl: 'https://harmonyai.app/',
            platform: 'macOS',
            category: 'AI Assistant',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282078/snapcloud/example25.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 713,
            createdAt: new Date('2024-03-11').toISOString(),
        },
        {
            name: 'NordPass',
            slug: 'nordpass',
            description: 'Secure password manager with encryption. Store and autofill passwords safely.',
            shortDescription: 'Secure password manager with encryption. Store a...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282082/snapcloud/example26.png',
            downloadUrl: 'https://nordpass.com/',
            platform: 'macOS',
            category: 'Password Manager',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282082/snapcloud/example26.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 589,
            createdAt: new Date('2024-04-27').toISOString(),
        },
        {
            name: 'Tella',
            slug: 'tella',
            description: 'Record edit and share beautiful videos. Perfect for tutorials and presentations.',
            shortDescription: 'Record edit and share beautiful videos. Perfect ...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282086/snapcloud/example27.png',
            downloadUrl: 'https://tella.tv/',
            platform: 'macOS',
            category: 'Screen Recording',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282086/snapcloud/example27.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 441,
            createdAt: new Date('2024-05-16').toISOString(),
        },
        {
            name: 'OneTap',
            slug: 'onetap',
            description: 'Execute complex actions with a single tap. Automate your workflow efficiently.',
            shortDescription: 'Execute complex actions with a single tap. Autom...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282090/snapcloud/example28.png',
            downloadUrl: 'https://onetap.app/',
            platform: 'macOS',
            category: 'Quick Actions',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282090/snapcloud/example28.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 256,
            createdAt: new Date('2024-06-04').toISOString(),
        },
        {
            name: 'Icon Preview',
            slug: 'icon-preview',
            description: 'Preview and test app icons instantly. See how your icons look on different devices.',
            shortDescription: 'Preview and test app icons instantly. See how yo...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282094/snapcloud/example29.png',
            downloadUrl: 'https://iconpreview.app/',
            platform: 'macOS',
            category: 'Design Tool',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282094/snapcloud/example29.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 329,
            createdAt: new Date('2024-07-22').toISOString(),
        },
        {
            name: 'Fabric',
            slug: 'fabric',
            description: 'Personal internet and file organizer. Capture thoughts and ideas beautifully.',
            shortDescription: 'Personal internet and file organizer. Capture th...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282098/snapcloud/example30.png',
            downloadUrl: 'https://fabric.so/',
            platform: 'macOS',
            category: 'Note Taking',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282098/snapcloud/example30.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 612,
            createdAt: new Date('2024-08-10').toISOString(),
        },
        {
            name: 'Dropnotch',
            slug: 'dropnotch',
            description: 'Transform your MacBook notch into a useful tool. Display notifications and controls.',
            shortDescription: 'Transform your MacBook notch into a useful tool....',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282102/snapcloud/example31.png',
            downloadUrl: 'https://dropnotch.app/',
            platform: 'macOS',
            category: 'Notch Utility',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282102/snapcloud/example31.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 467,
            createdAt: new Date('2024-09-01').toISOString(),
        },
        {
            name: 'TheBoringNotch',
            slug: 'theboringnotch',
            description: 'Make your notch productive with widgets and shortcuts. Maximize screen real estate.',
            shortDescription: 'Make your notch productive with widgets and shor...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282106/snapcloud/example32.png',
            downloadUrl: 'https://theboringnotch.app/',
            platform: 'macOS',
            category: 'Notch Tool',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282106/snapcloud/example32.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 534,
            createdAt: new Date('2024-09-19').toISOString(),
        },
        {
            name: 'Folder Hub',
            slug: 'folder-hub',
            description: 'Organize files and folders intelligently. Smart tagging and quick access.',
            shortDescription: 'Organize files and folders intelligently. Smart ...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282110/snapcloud/example33.png',
            downloadUrl: 'https://folderhub.app/',
            platform: 'macOS',
            category: 'File Organization',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282110/snapcloud/example33.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 298,
            createdAt: new Date('2024-10-07').toISOString(),
        },
        {
            name: 'Klack',
            slug: 'klack',
            description: 'Add satisfying keyboard sounds to your typing. Multiple sound profiles available.',
            shortDescription: 'Add satisfying keyboard sounds to your typing. M...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282114/snapcloud/example34.png',
            downloadUrl: 'https://klack.app/',
            platform: 'macOS',
            category: 'Keyboard Sound',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282114/snapcloud/example34.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 401,
            createdAt: new Date('2024-10-26').toISOString(),
        },
        {
            name: 'Craft',
            slug: 'craft',
            description: 'Beautiful document editor for notes projects and collaboration. Native design.',
            shortDescription: 'Beautiful document editor for notes projects and...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282118/snapcloud/example35.png',
            downloadUrl: 'https://craft.do/',
            platform: 'macOS',
            category: 'Document Editor',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282118/snapcloud/example35.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 778,
            createdAt: new Date('2024-11-13').toISOString(),
        },
        {
            name: 'Typeface',
            slug: 'typeface',
            description: 'Modern font manager for designers. Browse and manage your font library.',
            shortDescription: 'Modern font manager for designers. Browse and ma...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282122/snapcloud/example36.png',
            downloadUrl: 'https://typefaceapp.com/',
            platform: 'macOS',
            category: 'Font Manager',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282122/snapcloud/example36.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 345,
            createdAt: new Date('2024-12-01').toISOString(),
        },
        {
            name: 'HoldSpeak',
            slug: 'holdspeak',
            description: 'Push-to-talk for Mac. Control when your microphone is active during calls.',
            shortDescription: 'Push-to-talk for Mac. Control when your micropho...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282126/snapcloud/example37.png',
            downloadUrl: 'https://holdspeak.app/',
            platform: 'macOS',
            category: 'Voice Tool',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282126/snapcloud/example37.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 419,
            createdAt: new Date('2024-12-18').toISOString(),
        },
        {
            name: 'Obsidian',
            slug: 'obsidian',
            description: 'Powerful knowledge base on local Markdown files. Build your second brain.',
            shortDescription: 'Powerful knowledge base on local Markdown files....',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282130/snapcloud/example38.png',
            downloadUrl: 'https://obsidian.md/',
            platform: 'macOS',
            category: 'Knowledge Base',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282130/snapcloud/example38.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 687,
            createdAt: new Date('2023-01-23').toISOString(),
        },
        {
            name: 'Loom',
            slug: 'loom',
            description: 'Quick video messages for work. Record and share videos instantly.',
            shortDescription: 'Quick video messages for work. Record and share ...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282134/snapcloud/example39.png',
            downloadUrl: 'https://loom.com/',
            platform: 'macOS',
            category: 'Video Messaging',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282134/snapcloud/example39.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 745,
            createdAt: new Date('2023-03-09').toISOString(),
        },
        {
            name: 'Tana',
            slug: 'tana',
            description: 'AI-powered workspace for your thoughts. Connect ideas and build knowledge.',
            shortDescription: 'AI-powered workspace for your thoughts. Connect ...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282138/snapcloud/example40.png',
            downloadUrl: 'https://tana.inc/',
            platform: 'macOS',
            category: 'Knowledge Management',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282138/snapcloud/example40.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 523,
            createdAt: new Date('2023-04-27').toISOString(),
        },
        {
            name: 'Screenshot Studio',
            slug: 'screenshot-studio',
            description: 'Create beautiful screenshots with backgrounds and shadows. Perfect for marketing.',
            shortDescription: 'Create beautiful screenshots with backgrounds an...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282142/snapcloud/example41.png',
            downloadUrl: 'https://screenshotstudio.app/',
            platform: 'macOS',
            category: 'Screenshot Tool',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282142/snapcloud/example41.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 412,
            createdAt: new Date('2023-06-15').toISOString(),
        },
        {
            name: 'Texts',
            slug: 'texts',
            description: 'All your messages in one place. Connect multiple messaging apps.',
            shortDescription: 'All your messages in one place. Connect multiple...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282146/snapcloud/example42.png',
            downloadUrl: 'https://texts.com/',
            platform: 'macOS',
            category: 'Messaging Hub',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282146/snapcloud/example42.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 598,
            createdAt: new Date('2023-08-02').toISOString(),
        },
        {
            name: 'Slashit App',
            slug: 'slashit-app',
            description: 'Quick command palette for your most used actions. Boost productivity with shortcuts.',
            shortDescription: 'Quick command palette for your most used actions...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282150/snapcloud/example43.png',
            downloadUrl: 'https://slashit.app/',
            platform: 'macOS',
            category: 'Productivity',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282150/snapcloud/example43.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 367,
            createdAt: new Date('2023-09-20').toISOString(),
        },
        {
            name: 'ScreenStory',
            slug: 'screenstory',
            description: 'Beautiful screen recordings with automatic zoom and focus. Perfect for demos.',
            shortDescription: 'Beautiful screen recordings with automatic zoom ...',
            developer: 'Unknown',
            iconUrl: 'https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282154/snapcloud/example44.png',
            downloadUrl: 'https://screenstory.app/',
            platform: 'macOS',
            category: 'Screen Recording',
            screenshots: ['https://res.cloudinary.com/dmoxo9sj4/image/upload/v1764282154/snapcloud/example44.png', 'https://via.placeholder.com/800x600/1a1a1a/ffffff?text=Screenshot+2', 'https://via.placeholder.com/800x600/2a2a2a/ffffff?text=Screenshot+3', 'https://via.placeholder.com/800x600/3a3a3a/ffffff?text=Screenshot+4'],
            rating: 4.5,
            reviewsCount: 492,
            createdAt: new Date('2023-11-08').toISOString(),
        },
    ];

    await db.insert(apps).values(sampleApps);
    
    console.log('✅ Apps seeder completed successfully - 54 FREE apps added');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});